#!/usr/bin/env bash
# Generate the deployment identity and the client-side diary manifest.

set -euo pipefail

DAY_ONE_DATE="${DAY_ONE_DATE:-2026-08-05}" # PLACEHOLDER — set at launch

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if SHA="$(git rev-parse HEAD 2>/dev/null)" && [[ -n "$SHA" ]]; then
  :
else
  SHA="no-commits-yet"
fi
SHORT_SHA="${SHA:0:7}"
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TODAY_ISO="$(date -u +%Y-%m-%d)"

DAY_N="$(python3 - "$DAY_ONE_DATE" "$TODAY_ISO" <<'PY'
import datetime
import sys

day_one = datetime.date.fromisoformat(sys.argv[1])
today = datetime.date.fromisoformat(sys.argv[2])
print(max(0, (today - day_one).days + 1))
PY
)"
DAY_LABEL="Day ${DAY_N}"

printf '%s\n' "$SHA" > build-sha.txt

cat > build-sha.js <<JS
// Generated by scripts/build.sh. Do not hand-edit.
(function () {
  var SHA = "$SHA";
  var SHORT_SHA = "$SHORT_SHA";
  var BUILT_AT = "$BUILT_AT";
  var DAY_N = $DAY_N;
  var DAY_LABEL = "$DAY_LABEL";

  function applyBuild() {
    var meta = document.querySelector('meta[name="build-sha"]');
    if (meta) meta.setAttribute('content', SHA);

    var shaLabel = document.getElementById('build-sha-label');
    if (shaLabel) shaLabel.textContent = SHORT_SHA + ' · ' + BUILT_AT;

    var dayLabel = document.getElementById('day-label');
    if (dayLabel) dayLabel.textContent = DAY_LABEL;
  }

  window.__towerBuild = {
    sha: SHA,
    shortSha: SHORT_SHA,
    builtAt: BUILT_AT,
    dayN: DAY_N,
    dayLabel: DAY_LABEL
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', applyBuild, { once: true });
  } else {
    applyBuild();
  }
})();
JS

python3 - "$DAY_ONE_DATE" <<'PY'
import datetime
import json
import pathlib
import re
import sys

root = pathlib.Path("diary")
anchor = datetime.date.fromisoformat(sys.argv[1])
entries = []

def day_number(date_text):
    if date_text == "0000-00-00":
        return 0
    try:
        value = (datetime.date.fromisoformat(date_text) - anchor).days + 1
    except ValueError:
        return None
    return max(0, value)

for markdown in sorted(root.glob("*.md")):
    if markdown.name == "README.md":
        continue
    match = re.match(r"^(\d{4}-\d{2}-\d{2})(?:-.*)?\.md$", markdown.name)
    if not match:
        continue

    date_text = match.group(1)
    title = ""
    try:
        for line in markdown.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
    except OSError:
        pass

    day = day_number(date_text)
    entries.append({
        "date": date_text,
        "day": day,
        "kind": "daily",
        "label": f"Day {day}" if day is not None else date_text,
        "title": title,
        "path": markdown.name,
    })

manifest = root / "manifest.json"
manifest.write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
print(f"build: wrote {manifest} ({len(entries)} entries)")
PY

echo "build: SHA=$SHA"
echo "build: Day=$DAY_N (anchor $DAY_ONE_DATE)"
echo "build: wrote build-sha.txt and build-sha.js"
