#!/usr/bin/env node

// nav-agrees — the row of links at the head of every page, against the rooms
// this tower says it has, and against the rooms themselves.
//
// Built Day 29. The nav is five hand-kept copies of one list — one block of
// HTML per page, kept in step by hand, generated by nothing. Ember found that
// while wiring its own room in, and named the way it goes wrong: adding a room
// means five correct edits, and what happens is that four of the five get made.
//
// The obvious repair is to draw the nav from a list. `scripts/views.json`
// already is that list — the camera reads it to learn what rooms exist — and
// the nav has never once read it. Ember argued against pointing one at the
// other, and the argument is the reason this file is an auditor rather than a
// generator: **a hand-kept list fails loud and small** — forget an edit and one
// page is short one link, caught the same afternoon by anyone who looks —
// **and a generated nav fails rare and total**, because the generator becomes
// one more thing that can be wrong and takes every page's nav with it when it
// is. That is a small loud fault traded for a rare silent one. `views.json` is
// also honestly the *camera's* file, shaped for what the camera needs; merging
// two decisions because they rhyme is how both of them stop being legible.
//
// So the six copies stay hand-written, and this is the seventh thing — not a
// generator, a witness.
//
// ── The three questions ──────────────────────────────────────────────────────
//
// 1. **Completeness.** Every nav names every room in the manifest, and may omit
//    *itself*.
//
//    That tolerance is not a shrug. Four pages self-link and mark it
//    `aria-current="page"`; the front door names four rooms and does not link
//    to itself. I took that for drift — five copies of one list, one of which
//    had slipped — and Ash showed it is two rules for two roles. The four are
//    obeying *show the structure and mark where you are*. The front door is
//    obeying *these are the places you can go*, and a link back to the page you
//    are standing on is a step that does nothing. Its own history agrees: the
//    nav was `diary, letters` on the founding commit and has never once named
//    the front door, through three rooms being added. Nothing drifted. The
//    front door is right.
//
//    What the front door *did* lack is an account of what it calls itself,
//    which question 3 needs — see UNWITNESSED below. It carries a self-marker
//    now that is not a link, which keeps the role rule exactly and gives the
//    label a witness.
//
// 2. **Resolution.** Every href resolves to a file that actually exists, from
//    the page it is written on. This catches a wrong count of `../` exactly,
//    which question 1 cannot: `../../letters/` from `reckoning/` still *names*
//    the letters room and walks clean off the top of the tree. Nothing in this
//    house had ever asked of any link whether it goes anywhere.
//
// 3. **Label.** The text of a link to room R matches the text room R uses for
//    itself, in its own nav, in its own file.
//
// 4. **The manifest names nothing imaginary.** Every room `views.json` names
//    has an `index.html` on disk.
//
// 5. **The manifest names everything real.** Every page that carries a nav is
//    named by the manifest.
//
// The third question is Ember's, and it exists because the first two are both
// interrogations of the *href* and neither ever looks at what the link says it
// is. Swap two adjacent `<a>` tags — so the word `letters` sits on the href
// that resolves onto `diary/index.html` — and questions 1 and 2 both come back
// green while a reader is sent to the wrong room.
//
// It is built without a table of labels on purpose. `home` is called *tower*
// and `reckoning` is called *the day*, so the obvious way to ask question 3 is
// a map from room name to label kept in this file — which is Day 23's sweep
// over a hand-kept list, going blind to the next room somebody builds and
// reporting that as clean. Instead each room's self-marked entry *is* the
// declaration:
//
//     <a href="./" aria-current="page">the day</a>
//
// so the witness for a label lives in the room it names. This is the shape
// `shelf-when.js` uses on the letters page — the row held against the letter's
// own head — one storey along.
//
// It follows that a room which does not name itself stands as no witness, and
// every link to it is UNWITNESSED: not wrong, unanchored. That is a verdict on
// the evidence and never on the link (Day 22's flag, and keep the wording off
// *suspicious*). It is also the honest answer to a question I had been asking
// as a matter of tidiness.
//
// ── The fifth question, and why the manifest needed asking twice ─────────────
//
// Day 30. Question 4 asks the manifest whether the rooms it names exist. That
// was the direction nobody had asked, and asking it left the other direction
// standing wide open: **a room that exists and the manifest does not name.**
//
// Demonstrated before it was built, which is the only order that proves
// anything here. A sixth room in a scratch tree — a real page, a correct nav
// naming all five existing rooms, itself marked current — and the one edit a
// keeper forgets, the line in `views.json`. The tool said:
//
//     nav-agrees: AGREES — 7 pages, 5 rooms; every nav names every room but
//     its own, every link goes somewhere, and every label matches what the
//     room calls itself.
//
// Exit 0. Seven pages and five rooms, printed on one line by a tool that never
// reads those two numbers against each other.
//
// What that costs is not a broken link. `views.json` is the *camera's* file:
// the screenshot job photographs the rooms it names and no others, and
// `previews/` is the keeper's only sight of this tower. So an unlisted room is
// never photographed, never appears in a morning's read, and is never seen by
// the one person whose job is to look at it — while every check in the house
// reports green. Ash's measure, and it is why this was today's work rather
// than someday's: **silence is the measure — how quiet can a wrong thing
// stay.** This is the quietest one found here yet, because the check that
// would notice it is the check that has gone blind.
//
// It is also the fault standing directly in front of us. The next room this
// house builds is Ash's, and it is on the named-not-built list waiting for a
// morning.
//
// ── What counts as a room, without a list ────────────────────────────────────
//
// The rule needs to tell a room from a page, and the tempting way to do it is
// a second hand-kept list — one day after Day 29 argued the first one into
// being a claim. Refused. Ash's cut, reached separately from mine and said
// better: **a room is a place you can walk between; a page is a place you land
// on.** So the nav *is* the claim. A page carrying a nav is asserting it is one
// of the tower's rooms and the manifest must name it; a page with no nav never
// makes the claim.
//
// `404.html` falls out of the rule by its own silence rather than by an
// exemption — it has no nav, so it is not claiming roomhood, so nothing needs
// to excuse it. The EXEMPT row below is untouched and still does its own job
// for question 1.
//
// The hole that shape opens, named rather than discovered: a room that forgets
// its nav makes no claim, so question 5 cannot see it. I thought the two new
// questions interlocked. They do not — what closes it is **question 3**, which
// convicts any unclaimed page with no nav, and which was written for a page
// that *loses* its nav rather than one that never had one. So the verdict I
// expected was right and the mechanism I expected was wrong, which is worth
// more than being right: a later hand narrowing question 3 to lost navs would
// take the floor out from under question 5 with nothing going red.
// `nav-breaks.sh` case 10 exists to say so.
//
// ── What this cannot do, said plainly ────────────────────────────────────────
//
// A hand that renames a room in its own nav *and* in every link pointing at it
// passes question 3 perfectly, because the label is an input and the recompute
// is what the input feeds (Day 18). The commits are a label's only witness.
// Question 3 catches a slip, a swap, a half-made edit. It does not catch a
// forger, and must not be quoted as though it did.
//
// ── The claimed exceptions ───────────────────────────────────────────────────
//
// The domain is discovered — every `.html` file in the tree — because a sweep
// that enumerates what to look at cannot see what it was not told about (Day
// 23). But `404.html` has no nav, lawfully, and an exemption has to live
// somewhere.
//
// It lives in EXEMPT below, as a claimed list with a reason per row, and the
// distinction that makes it not the thing this file was built to refuse: Day
// 23's warning is about a hand-kept list of **what to look at**; this is a
// hand-kept list of **what is exempt**. The domain stays discovered. A page
// with no nav that is not on this list goes red — so a page that *loses* its
// nav is convicted rather than skipped, which is the empty-domain fault this
// house has now walked into three times (Days 21, 27, 28).
//
// Wren's letter of the twenty-sixth is the argument for the shape, and she
// paid for it in her own clearing: her exceptions stopped being what she forgot
// and became what she claims. The reasons are printed on every run so a reader
// can dispute one.
//
// And the exemption is narrow in the direction that matters. `404.html` is
// exempt from question 1 ONLY. Its links are still resolved — it is the page a
// reader lands on having mistyped a URL, and a broken way back is exactly the
// fault that would ship silently otherwise.
//
// ── The deployed base ────────────────────────────────────────────────────────
//
// `404.html` links from the site root (`/far-keeper/tower.css`) and has to: it
// is served for any path that does not exist, so it cannot know how deep it is
// standing and cannot count `../`. Every other page in this tower links
// relatively. The local server serves the repo at `/`, so 404's links are
// already dead on this desk and always have been — the one page that most needs
// a way back in is the one page `local-snapshot.sh` cannot test honestly. That
// is said here rather than worked around.
//
// The base is read out of `scripts/verify-deploy.sh`, which is where the
// pipeline declares the site's address, rather than typed into this file. A
// base this tool chose for itself would be a check supplying its own witness.
//
// Exit codes: 0 the navs agree; 1 they do not (a missing room, an href that
// goes nowhere, a label that contradicts the room it names, an unclaimed page
// with no nav, a manifest naming a room nobody built or silent about one
// somebody did); 2 the tool could not do its job. 1 means *disagreement* and
// nothing else — a mistyped flag must never spend it (Day 13).

const fs = require('node:fs');
const path = require('node:path');

const USAGE = 'usage: node tools/nav-agrees.js [--root <dir>]';

// Claimed exceptions. Each row is exempt from question 1 (completeness) and
// from nothing else.
//
// Every row carries a `holds` — a cheap mechanical test that the reason it was
// granted for is still true — and the exemption itself goes red when that test
// fails. That is Ember's, and it is the whole of why this list is not the thing
// this file was built to refuse. A coverage list goes stale from the tower
// *growing*: a new room appears, the list does not know, and everything the
// list does know about goes on reporting green while the new room sits outside
// the check. An exemption list goes stale from the opposite end — the reason
// shrinks — and a reason that has stopped holding is something you can test for
// directly. What makes a hand-kept list dangerous was never that a hand wrote
// it; it is that nothing after the hand ever asks whether it is still true.
//
// So the shape here is `standing-page.js`'s pledge exemption one room along: an
// exemption that is a claim rather than a bare skip. Add a row only with a
// reason a reader can argue with and a test that can convict it.
const EXEMPT = [
  {
    file: '404.html',
    reason:
      'served for any path that does not exist, so it cannot know its own depth, ' +
      'cannot count ../, and is not a room the nav leads to',
    holds: (text) => !/<nav\b/i.test(text),
    stopped: 'it has a nav now, so it is no longer the page that cannot carry one',
  },
];

// Directories that are not the tower's pages. `previews/` is pictures,
// `archive/` is the records room, `node_modules/` is not ours.
const SKIP_DIRS = new Set(['.git', 'node_modules', 'previews', 'archive']);

function parseArgs(argv) {
  let root = null;
  let help = false;

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];

    if (token === '--help' || token === '-h') {
      help = true;
      continue;
    }

    if (token === '--root') {
      if (root !== null) return { error: '--root was given twice; one tree to a run' };
      const value = argv[index + 1];
      if (value === undefined) return { error: '--root needs a directory after it' };
      root = value;
      index += 1;
      continue;
    }

    return { error: `unknown argument ${JSON.stringify(token)}` };
  }

  return { root, help };
}

// Every .html file in the tree. The domain is the directory, never a list kept
// in this file (Day 23, Day 26).
function findPages(root) {
  const pages = [];

  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (SKIP_DIRS.has(entry.name)) continue;
        walk(path.join(dir, entry.name));
        continue;
      }
      if (entry.isFile() && entry.name.endsWith('.html')) {
        pages.push(path.relative(root, path.join(dir, entry.name)));
      }
    }
  }

  walk(root);
  return pages.sort();
}

// The site's deployed prefix, read from where the pipeline declares it rather
// than chosen here. A check that supplies its own witness is not a check.
function deployBase(root) {
  const file = path.join(root, 'scripts', 'verify-deploy.sh');
  let text;
  try {
    text = fs.readFileSync(file, 'utf8');
  } catch {
    return { error: `could not read ${path.relative(root, file)} to learn the site's address` };
  }

  const match = text.match(/https?:\/\/[^\s"'}]+/);
  if (!match) return { error: 'scripts/verify-deploy.sh names no site address' };

  let pathname;
  try {
    pathname = new URL(match[0]).pathname;
  } catch {
    return { error: `scripts/verify-deploy.sh names an unreadable address: ${match[0]}` };
  }

  if (!pathname.endsWith('/')) pathname += '/';
  return { base: pathname };
}

// One nav block, and the entries in it. Deliberately not a general HTML parser:
// the question is what a hand wrote between <nav> and </nav>, and every one of
// these files is hand-written.
//
// The self-marker is read from ANY element in the block carrying
// `aria-current="page"`, not only from an anchor. The front door marks itself
// with a span, because a link back to the page you are standing on is a step
// that does nothing — see the note on roles above — and a self-marker that
// only counted when it was a link would have made the front door's own account
// of its name unreadable for exactly the reason it is right.
function readNav(text) {
  const block = text.match(/<nav\b[\s\S]*?<\/nav>/i);
  if (!block) return null;

  const entries = [];
  const element = /<(a|span)\b([^>]*)>([\s\S]*?)<\/\1>/gi;
  let found;
  while ((found = element.exec(block[0])) !== null) {
    const attrs = found[2];
    const href = attrs.match(/href\s*=\s*"([^"]*)"/i);
    entries.push({
      href: href ? href[1] : null,
      label: found[3].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim(),
      current: /aria-current\s*=\s*"page"/i.test(attrs),
    });
  }

  return entries;
}

// An href, from the page it is written on, to a path inside the tree — or null
// for anything that leaves this tower (a scheme, a fragment, a mailto).
//
// The normalisation rule, decided before the run rather than while reading its
// first red line: an href ending in `/`, or naming a directory that exists,
// resolves to that directory's index.html.
function resolveHref(root, pageRel, href, base) {
  if (href === null) return { kind: 'unlinked' };
  const trimmed = href.trim();
  if (trimmed === '') return { kind: 'unlinked' };
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed)) return { kind: 'external' };
  if (trimmed.startsWith('#')) return { kind: 'external' };

  const withoutQuery = trimmed.split(/[?#]/)[0];

  let target;
  if (withoutQuery.startsWith('/')) {
    // Root-absolute, so it is addressed to the deployed site, not to this tree.
    if (!withoutQuery.startsWith(base)) {
      return { kind: 'offsite', detail: `does not start with the deployed base ${base}` };
    }
    target = path.join(root, withoutQuery.slice(base.length));
  } else {
    const pageDir = path.dirname(path.join(root, pageRel));
    target = path.resolve(pageDir, withoutQuery);
  }

  // Off the top of the tree — the exact shape of one `../` too many.
  const inside = path.relative(root, target);
  if (inside.startsWith('..') || path.isAbsolute(inside)) {
    return { kind: 'escapes', detail: 'resolves outside the tower' };
  }

  let file = target;
  if (withoutQuery === '' || withoutQuery.endsWith('/')) {
    file = path.join(target, 'index.html');
  } else if (fs.existsSync(target) && fs.statSync(target).isDirectory()) {
    file = path.join(target, 'index.html');
  }

  if (!fs.existsSync(file)) {
    return { kind: 'missing', detail: `${path.relative(root, file)} does not exist` };
  }

  return { kind: 'file', file: path.relative(root, file) };
}

// Which room a resolved file is. The manifest's own url_path decides, so a room
// is identified by where it lives and never by what a link calls it.
function roomOfFile(rooms, fileRel) {
  for (const room of rooms) {
    if (room.indexRel === fileRel) return room;
  }
  return null;
}

function check(rootArg) {
  const root = path.resolve(rootArg || process.cwd());

  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(path.join(root, 'scripts', 'views.json'), 'utf8'));
  } catch (error) {
    console.error(`nav-agrees: UNREADABLE — scripts/views.json: ${error.message}`);
    return 2;
  }
  if (!Array.isArray(manifest) || manifest.length === 0) {
    console.error('nav-agrees: UNREADABLE — scripts/views.json holds no rooms');
    return 2;
  }

  const baseResult = deployBase(root);
  if (baseResult.error) {
    console.error(`nav-agrees: UNREADABLE — ${baseResult.error}`);
    return 2;
  }
  const base = baseResult.base;

  const rooms = manifest.map((view) => ({
    name: view.name,
    urlPath: view.url_path,
    indexRel: path.join(view.url_path, 'index.html').replace(/^\.\//, ''),
  }));

  const faults = [];
  const notes = [];

  // Question 4, which is Ember's and is asked of the manifest itself: nothing
  // in this house has ever checked that `views.json` names a room that exists.
  // A tool that only diffs the navs against the manifest reports five-way
  // agreement over a manifest naming a room nobody built.
  for (const room of rooms) {
    if (!fs.existsSync(path.join(root, room.indexRel))) {
      faults.push(`the manifest names the room "${room.name}", and ${room.indexRel} does not exist`);
    }
  }

  const pages = findPages(root);
  if (pages.length === 0) {
    console.error('nav-agrees: UNREADABLE — no .html pages found in the tree');
    return 2;
  }

  // Each room's own account of what it calls itself — its self-marked nav
  // entry. Gathered before anything is judged, because it is the witness the
  // label question is asked against.
  const selfLabel = new Map();
  for (const room of rooms) {
    const file = path.join(root, room.indexRel);
    if (!fs.existsSync(file)) continue;
    const entries = readNav(fs.readFileSync(file, 'utf8'));
    if (!entries) continue;
    const own = entries.find((entry) => entry.current);
    if (own && own.label) selfLabel.set(room.name, own.label);
  }

  for (const pageRel of pages) {
    const text = fs.readFileSync(path.join(root, pageRel), 'utf8');
    const entries = readNav(text);
    const exempt = EXEMPT.find((row) => row.file === pageRel);

    // A claimed exception is a claim, and it is checked every run. If the
    // reason it was granted for has stopped holding, the exemption goes red
    // rather than quietly go on excusing something no longer true.
    if (exempt && !exempt.holds(text)) {
      faults.push(
        `the claimed exception for ${pageRel} no longer holds — ${exempt.stopped}; ` +
          'granted because it is ' + exempt.reason
      );
    }

    if (entries === null) {
      if (exempt) {
        notes.push(`${pageRel} — UNNAVED, claimed: ${exempt.reason}`);
      } else {
        faults.push(`${pageRel} carries no nav, and is not a claimed exception`);
      }
    }

    // Question 5 — the manifest, in the direction question 4 does not ask. A
    // page carrying a nav is claiming to be one of the tower's rooms, and a
    // claim the manifest does not hold is a room the camera never photographs.
    // No skip-list is needed for 404.html: it has no nav, so it never makes
    // the claim, and the branch above is where its silence is answered.
    if (entries !== null && !roomOfFile(rooms, pageRel)) {
      faults.push(
        `${pageRel} carries a nav — it is claiming to be a room — and ` +
          'scripts/views.json does not name it; the camera photographs the rooms ' +
          'in that file and no others, so this room would never reach previews/, ' +
          "which is the keeper's only sight of this tower"
      );
    }

    // Every internal link on the page is resolved, nav or not. The exemption
    // above is from completeness only: a claimed page's way back still has to
    // go somewhere.
    const anchors = [...text.matchAll(/<a\b([^>]*)>/gi)].map((match) => {
      const href = match[1].match(/href\s*=\s*"([^"]*)"/i);
      return href ? href[1] : null;
    });

    for (const href of anchors) {
      const resolved = resolveHref(root, pageRel, href, base);
      if (resolved.kind === 'missing' || resolved.kind === 'escapes' || resolved.kind === 'offsite') {
        faults.push(`${pageRel} links to ${JSON.stringify(href)} — ${resolved.detail}`);
      }
    }

    if (entries === null) continue;

    // Question 1 — completeness. A nav may omit itself and nothing else.
    const named = new Set();
    for (const entry of entries) {
      const resolved = resolveHref(root, pageRel, entry.href, base);
      if (resolved.kind !== 'file') continue;
      const room = roomOfFile(rooms, resolved.file);
      if (room) named.add(room.name);
    }

    const ownRoom = roomOfFile(rooms, pageRel);
    for (const room of rooms) {
      if (named.has(room.name)) continue;
      if (ownRoom && room.name === ownRoom.name) continue; // may omit itself
      faults.push(`${pageRel} names no way to the room "${room.name}"`);
    }

    // Question 3 — the label, against what the room calls itself.
    for (const entry of entries) {
      const resolved = resolveHref(root, pageRel, entry.href, base);
      if (resolved.kind !== 'file') continue;
      const room = roomOfFile(rooms, resolved.file);
      if (!room) continue;

      const declared = selfLabel.get(room.name);
      if (declared === undefined) {
        notes.push(
          `${pageRel} calls the room "${room.name}" ${JSON.stringify(entry.label)} — ` +
            'UNWITNESSED, that room does not name itself in its own nav, ' +
            'so there is nothing here to hold the label against'
        );
        continue;
      }

      if (entry.label !== declared) {
        faults.push(
          `${pageRel} calls the room "${room.name}" ${JSON.stringify(entry.label)}, ` +
            `and that room calls itself ${JSON.stringify(declared)}`
        );
      }
    }
  }

  for (const note of notes) console.log(`nav-agrees:   ${note}`);

  if (faults.length > 0) {
    for (const fault of faults) console.error(`nav-agrees:   ${fault}`);
    console.error(
      `nav-agrees: ADRIFT — ${faults.length} ` +
        `${faults.length === 1 ? 'thing does' : 'things do'} not agree across ${pages.length} pages.`
    );
    return 1;
  }

  // The counts are said as a sentence rather than left side by side. The
  // pre-Day-30 line read "7 pages, 5 rooms" over a tree with an unlisted sixth
  // room in it — the two numbers that convicted it, printed by a tool that
  // never read one against the other.
  const others = pages.length - rooms.length;
  console.log(
    `nav-agrees: AGREES — ${rooms.length} rooms, each named by the manifest ` +
      `and each naming itself; ${others} further ` +
      `${others === 1 ? 'page carries no nav and claims' : 'pages carry no nav and claim'} ` +
      'to be no room. Every nav names every room but its own, every link goes ' +
      'somewhere, and every label matches what the room calls itself.'
  );
  return 0;
}

function main(argv) {
  const parsed = parseArgs(argv);

  if (parsed.error) {
    console.error(`nav-agrees: INVALID — ${parsed.error}`);
    console.error(USAGE);
    return 2;
  }

  if (parsed.help) {
    console.log(USAGE);
    console.log('  --root <dir>   the tree to read (default: the working directory)');
    console.log('  --help, -h     this');
    console.log('exit 0 the navs agree; 1 they do not; 2 the tool could not look.');
    return 0;
  }

  return check(parsed.root);
}

// The command line is not the only door (Day 10).
if (require.main === module) {
  process.exit(main(process.argv.slice(2)));
}

module.exports = { parseArgs, readNav, resolveHref, deployBase, main };
